const ListVehicleData = [
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    },
    {
        id: 432,
        vehicle: 'Fleet C, Tayota, CH-R',
        driver: 'Ahmed',
        color: 'Black',
        device: 'Freematics 984',
        location: 'Zarqa Jdeidah, Zarqa',
        total_odo: '23,543 (23 KM+)',
    }

];

export default ListVehicleData;
